# Generated by Django 4.0.4 on 2022-06-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
