# Generated by Django 4.0.4 on 2022-06-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='statut',
        ),
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
